#NAME: Ryan Wakefield
#EMAIL: ryanwakefield@g.ucla.edu
#ID: 904975422

default:
	gcc -lmraa -lm -Wall -Wextra -o lab4b lab4b.c

clean:
	rm -f lab4b lab4b-904975422.tar.gz

dist:
	tar -czf lab4b-904975422.tar.gz README lab4b.c Makefile smoke.sh

check:
	./smoke.sh	
